using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Adam.Shared.Models;
using Adam.Shared.Services;
using Microsoft.EntityFrameworkCore;

namespace Adam.CatalogBrowser.ViewModels;

/// <summary>
/// ViewModel for the auto-album generation dialog.
/// Manages clustering parameters, preview, and album creation.
/// </summary>
public sealed class AutoAlbumViewModel : INotifyPropertyChanged
{
    private readonly EmbeddingClusterService _clusterService;
    private readonly ModeManager _modeManager;
    private bool _isComputing;
    private string _progressText = string.Empty;
    private int _minClusterSize = 3;
    private int _maxClusters = 20;
    private double _sensitivity = 0.75;
    private int _selectedSourceIndex;
    private int _selectedModeIndex = 0; // 0 = Images only, 1 = All assets
    private IReadOnlyList<AlbumCluster> _previewClusters = [];
    private string _statusText = string.Empty;

    public AutoAlbumViewModel(
        EmbeddingClusterService clusterService,
        ModeManager modeManager)
    {
        _clusterService = clusterService;
        _modeManager = modeManager;

        ComputePreviewCommand = new RelayCommand(async _ => await ComputePreviewAsync());
        CreateAlbumsCommand = new RelayCommand(async _ => await CreateAlbumsAsync(), _ => _previewClusters.Count > 0);
        CloseCommand = new RelayCommand(_ => Close());
    }

    /// <summary>
    /// Source scope for clustering.
    /// </summary>
    public IReadOnlyList<string> SourceOptions { get; } = new[] { "All assets", "Last 30 days", "Selected assets" };

    /// <summary>
    /// Selected source scope index.
    /// </summary>
    public int SelectedSourceIndex
    {
        get => _selectedSourceIndex;
        set { _selectedSourceIndex = value; OnPropertyChanged(); }
    }

    /// <summary>
    /// Mode: Images only (0) or All assets (1).
    /// </summary>
    public int SelectedModeIndex
    {
        get => _selectedModeIndex;
        set { _selectedModeIndex = value; OnPropertyChanged(); }
    }

    /// <summary>
    /// Similarity threshold sensitivity (0.6-0.95).
    /// </summary>
    public double Sensitivity
    {
        get => _sensitivity;
        set
        {
            _sensitivity = Math.Clamp(value, 0.6, 0.95);
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Minimum number of assets per cluster.
    /// </summary>
    public int MinClusterSize
    {
        get => _minClusterSize;
        set
        {
            _minClusterSize = Math.Clamp(value, 2, 20);
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Maximum number of clusters to generate.
    /// </summary>
    public int MaxClusters
    {
        get => _maxClusters;
        set
        {
            _maxClusters = Math.Clamp(value, 5, 50);
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Whether computation is in progress.
    /// </summary>
    public bool IsComputing
    {
        get => _isComputing;
        set { _isComputing = value; OnPropertyChanged(); }
    }

    /// <summary>
    /// Progress text during computation.
    /// </summary>
    public string ProgressText
    {
        get => _progressText;
        set { _progressText = value; OnPropertyChanged(); }
    }

    /// <summary>
    /// Status text shown in the dialog.
    /// </summary>
    public string StatusText
    {
        get => _statusText;
        set { _statusText = value; OnPropertyChanged(); }
    }

    /// <summary>
    /// Preview clusters generated by the algorithm.
    /// </summary>
    public IReadOnlyList<AlbumCluster> PreviewClusters
    {
        get => _previewClusters;
        set
        {
            _previewClusters = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(HasClusters));
            (CreateAlbumsCommand as RelayCommand)?.RaiseCanExecuteChanged();
        }
    }

    /// <summary>
    /// Whether any clusters were found.
    /// </summary>
    public bool HasClusters => _previewClusters.Count > 0;

    public ICommand ComputePreviewCommand { get; }
    public ICommand CreateAlbumsCommand { get; }
    public ICommand CloseCommand { get; }

    /// <summary>
    /// Computes the cluster preview without creating albums.
    /// </summary>
    public async Task ComputePreviewAsync(CancellationToken ct = default)
    {
        IsComputing = true;
        ProgressText = "Computing clusters...";
        StatusText = string.Empty;

        try
        {
            _clusterService.MinSimilarity = _sensitivity;
            _clusterService.MinClusterSize = _minClusterSize;
            _clusterService.MaxClusters = _maxClusters;

            var progress = new Progress<(int completed, int total)>(p =>
            {
                ProgressText = $"Clustering... ({p.completed}/{p.total})";
            });

            IReadOnlyList<Guid>? assetIds = null;
            if (SelectedSourceIndex == 1) // Last 30 days
            {
                // Would filter by date range — for now, use all
            }
            // Selected assets would be passed from MainWindowViewModel

            var clusters = await _clusterService.ClusterAsync(assetIds, progress, ct);
            PreviewClusters = clusters;

            StatusText = clusters.Count > 0
                ? $"Found {clusters.Count} album clusters"
                : "No clusters found — try lowering the similarity threshold";
        }
        catch (Exception ex)
        {
            StatusText = $"Clustering failed: {ex.Message}";
        }
        finally
        {
            IsComputing = false;
        }
    }

    /// <summary>
    /// Creates smart collections from the preview clusters.
    /// </summary>
    public async Task CreateAlbumsAsync(CancellationToken ct = default)
    {
        if (_previewClusters.Count == 0) return;

        try
        {
            await using var db = await _modeManager.CreateDbContextAsync(ct);

            foreach (var cluster in _previewClusters)
            {
                // Create a smart collection with centroid data in SmartQueryJson
                var collection = new Collection
                {
                    Id = Guid.NewGuid(),
                    Name = cluster.SuggestedName.Length > 200
                        ? cluster.SuggestedName[..200]
                        : cluster.SuggestedName,
                    Description = $"Auto-generated album with {cluster.Assets.Count} assets",
                    IsSmart = true,
                    SmartQueryJson = System.Text.Json.JsonSerializer.Serialize(new
                    {
                        type = "embedding_cluster",
                        minSimilarity = _sensitivity,
                        assetCount = cluster.Assets.Count,
                        centroidSimilarity = cluster.CentroidSimilarity,
                        keywords = cluster.CommonKeywords
                    }),
                    CreatedAt = DateTimeOffset.UtcNow
                };

                db.Collections.Add(collection);

                // Add assets to the collection
                var assetIds = cluster.Assets.Select(a => a.AssetId).ToList();
                var digitalAssets = await db.DigitalAssets
                    .Where(a => assetIds.Contains(a.Id))
                    .ToListAsync(ct);

                foreach (var asset in digitalAssets)
                {
                    collection.Assets.Add(asset);
                }
            }

            await db.SaveChangesAsync(ct);

            StatusText = $"Created {_previewClusters.Count} smart album(s)";
            AlbumsCreated?.Invoke(_previewClusters.Count);
        }
        catch (Exception ex)
        {
            StatusText = $"Failed to create albums: {ex.Message}";
        }
    }

    /// <summary>
    /// Fired when albums are successfully created.
    /// </summary>
    public event Action<int>? AlbumsCreated;

    /// <summary>
    /// Fired when the user closes the dialog.
    /// </summary>
    public event Action? CloseRequested;

    private void Close() => CloseRequested?.Invoke();

    public event PropertyChangedEventHandler? PropertyChanged;
    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}
